"""shindan_id_type

迁移 ID: fdc15c338ecc
父迁移: 0b2f6bf54834
创建时间: 2024-03-03 13:47:11.231471

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fdc15c338ecc"
down_revision: str | Sequence[str] | None = "0b2f6bf54834"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_shindan_shindanrecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "shindan_id",
            existing_type=sa.VARCHAR(length=32),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="shindan_id::integer",
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_shindan_shindanrecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "shindan_id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=32),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
